Repository brilliantshell/miniRT, pull requests merged in 2021-12, with the labels that each got.

#14 m_fix : marked z direction problems & refactored phong_light.c
  include/minirt.h
  src/render/intersect_pl.c
  src/render/intersect_sph.c
  src/render/phong_light.c
  src/render/ray_tracing.c
  src/render/vect_ops.c
  src/render/view_transform.c
  test_sphere.rt
Labels: enhancement

#17 m_fix : fix err in transf matrix
  basic.rt
  src/render/ray_tracing.c
  src/render/view_transform.c
Labels: enhancement

#19 m_feat : change fov in .rt files :)
  basic.rt
  sph.rt
  src/render/init_struct.c
  src/render/intersect_sph.c
  src/render/ray_tracing.c
  src/render/vect_ops.c
  test_sphere.rt
Labels: enhancement

#21 Shadow on! & Leak Fix & Refactor
  Makefile
  basic.rt
  include/minirt.h
  include/structs.h
  sph.rt
  src/main.c
  src/parse/obj_lst.c
  src/parse/parse_main.c
  src/render/create_cy_img.c
  src/render/create_pl_img.c
  src/render/create_sph_img.c
  src/render/img_util.c
  src/render/intersect_cy.c
  src/render/intersect_pl.c
  src/render/intersect_sph.c
  src/render/phong_light.c
  src/render/ray_tracing.c
  src/render/shadow.c
  src/render/vect_util.c
  src/render/view_transform.c
  test_shadow.rt
Labels: enhancement

#26 Fix shadow of sphere
  include/minirt.h
  pl_btw_light.rt
  pl_shadow.rt
  sph.rt
  sph_shadow.rt
  src/render/intersect_pl.c
  src/render/intersect_sph.c
  src/render/ray_tracing.c
  src/render/shadow.c
  src/render/view_transform.c
Labels: enhancement

#28 m_fix : fix when camera and plane orient the same direction
  pl_btw_light.rt
  sph_shadow.rt
  src/render/intersect_pl.c
  src/render/intersect_sph.c
  src/render/phong_light.c
  src/render/ray_tracing.c
  src/render/shadow.c
Labels: enhancement

#30 m_fix : fix when light intersect with obj
  src/parse/parse_main.c
  src/render/intersect_pl.c
  src/render/intersect_sph.c
  src/render/phong_light.c
  src/render/shadow.c
  test_sphere.rt
Labels: enhancement

#31 m_fix : add details to parse error message & comma parse error fix
  Makefile
  include/minirt.h
  lib/libft/ft_atod.c
  parse.rt
  src/parse/check_commas.c
  src/parse/fill_cy.c
  src/parse/fill_setting.c
  src/parse/fill_sph_pl.c
  src/parse/parse_main.c
Labels: enhancement

#33 m_fix : fix equation
  include/minirt.h
  src/render/intersect_cy.c
  src/render/shadow.c
  test.rt
Labels: bug

#34 m_fix : cy side
  src/render/intersect_cy.c
  src/render/phong_light.c
  test.rt
Labels: enhancement

#39 m_feat : add specular light
  Makefile
  cy_test.rt
  include/minirt.h
  sph.rt
  src/render/img_util.c
  src/render/phong_light.c
  src/render/phong_util.c
  src/render/shadow.c
  test.rt
Labels: enhancement

#40 Cylinder shadow draft + specular light
  include/minirt.h
  math2.c
  src/render/intersect_cy.c
  src/render/ray_tracing.c
  src/render/shadow.c
  test.rt
Labels: enhancement

#41 And yet it moves.
  Makefile
  basic.rt
  include/minirt.h
  src/main.c
  src/render/hook_minirt.c
  src/render/intersect_cy.c
  src/render/view_transform.c
  test.rt
Labels: enhancement

#43 m_feat : clone t_rt everytime when key hook event occurs
  Makefile
  cy_test.rt
  include/minirt.h
  include/structs.h
  src/main.c
  src/parse/obj_lst.c
  src/render/clone_rt.c
  src/render/hook_minirt.c
  src/render/init_struct.c
  src/render/intersect_cy.c
Labels: enhancement

#44 New feature : Camera move
  basic.rt
  include/minirt.h
  include/structs.h
  src/main.c
  src/render/hook_minirt.c
  src/render/view_transform.c
Labels: enhancement

#45 m_fix : fix theta rotation
  Makefile
  basic.rt
  include/minirt.h
  src/main.c
  src/render/cam_hook.c
  src/render/hook_minirt.c
  src/render/intersect_sph.c
  src/render/vect_util.c
  src/render/view_transform.c
Labels: enhancement

#48 m_feat : cylinder shadow done
  Makefile
  cy_on_sph_shadow.rt
  cy_shadow.rt
  include/minirt.h
  include/structs.h
  src/parse/fill_cy.c
  src/parse/parse_main.c
  src/render/clone_rt.c
  src/render/intersect_cy.c
  src/render/intersect_cy_circle.c
  src/render/intersect_pl.c
  src/render/phong_light.c
  src/render/ray_tracing.c
  src/render/shadow.c
  src/render/vect_util.c
  src/render/view_transform.c
Labels: enhancement

#52 Create bonus files
  Makefile
  basic.rt
  include/bonus/get_next_line_bonus.h
  include/bonus/minirt_bonus.h
  include/bonus/structs_bonus.h
  include/mandatory/get_next_line.h
  include/mandatory/minirt.h
  include/mandatory/structs.h
  src/bonus/main_bonus.c
  src/bonus/parse/check_commas_bonus.c
  src/bonus/parse/conf_lst_bonus.c
  src/bonus/parse/fill_cy_bonus.c
  src/bonus/parse/fill_setting_bonus.c
  src/bonus/parse/fill_sph_pl_bonus.c
  src/bonus/parse/get_next_line_bonus.c
  src/bonus/parse/get_next_line_utils_bonus.c
  src/bonus/parse/obj_lst_bonus.c
  src/bonus/parse/parse_main_bonus.c
  src/bonus/render/cam_hook_bonus.c
  src/bonus/render/clone_rt_bonus.c
  src/bonus/render/hook_minirt_bonus.c
  src/bonus/render/img_util_bonus.c
  src/bonus/render/init_struct_bonus.c
  src/bonus/render/intersect_cy_bonus.c
  src/bonus/render/intersect_cy_circle_bonus.c
  src/bonus/render/intersect_pl_bonus.c
  src/bonus/render/intersect_sph_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/bonus/render/shadow_bonus.c
  src/bonus/render/vect_ops_bonus.c
  src/bonus/render/vect_util_bonus.c
  src/bonus/render/view_transform_bonus.c
  src/mandatory/main.c
  src/mandatory/parse/check_commas.c
  src/mandatory/parse/conf_lst.c
  src/mandatory/parse/fill_cy.c
  src/mandatory/parse/fill_setting.c
  src/mandatory/parse/fill_sph_pl.c
  src/mandatory/parse/get_next_line.c
  src/mandatory/parse/get_next_line_utils.c
  src/mandatory/parse/obj_lst.c
  src/mandatory/parse/parse_main.c
  src/mandatory/render/cam_hook.c
  src/mandatory/render/clone_rt.c
  src/mandatory/render/hook_minirt.c
  src/mandatory/render/img_util.c
  src/mandatory/render/init_struct.c
  src/mandatory/render/intersect_cy.c
  src/mandatory/render/intersect_cy_circle.c
  src/mandatory/render/intersect_pl.c
  src/mandatory/render/intersect_sph.c
  src/mandatory/render/phong_light.c
  src/mandatory/render/phong_util.c
  src/mandatory/render/ray_tracing.c
  src/mandatory/render/shadow.c
  src/mandatory/render/vect_ops.c
  src/mandatory/render/vect_util.c
  src/mandatory/render/view_transform.c
Labels: enhancement

#54 New Feat : multithreading!
  .github/workflows/build_minirt.yml
  Makefile
  include/bonus/minirt_bonus.h
  include/bonus/structs_bonus.h
  include/mandatory/minirt.h
  include/mandatory/structs.h
  rt/basic.rt
  rt/cy_on_sph_shadow.rt
  rt/cy_shadow.rt
  rt/cy_test.rt
  rt/parse.rt
  rt/pl_btw_light.rt
  rt/pl_shadow.rt
  rt/sph.rt
  rt/sph_shadow.rt
  rt/test.rt
  rt/test_shadow.rt
  rt/test_sphere.rt
  src/bonus/main_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/mandatory/main.c
  src/mandatory/render/ray_tracing.c
Labels: enhancement

#58 b_feat : add cn
  rt/cn_basic.rt
  rt/hy_basic.rt
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/phong_light_bonus.c
Labels: enhancement

#59 b_feat : add cn bottom and shadow (dont work well)
  Makefile
  include/bonus/minirt_bonus.h
  include/bonus/structs_bonus.h
  rt/cn_basic.rt
  src/bonus/parse/fill_cone_bonus.c
  src/bonus/render/init_struct_bonus.c
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/intersect_cy_circle_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/bonus/render/shadow_bonus.c
  src/bonus/render/vect_ops_bonus.c
  src/mandatory/render/intersect_cy_circle.c
Labels: enhancement

#61 Add circle on cone
  etc/rt/cn_basic.rt
  include/bonus/minirt_bonus.h
  src/bonus/parse/fill_cone_bonus.c
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/bonus/render/shadow_bonus.c
  src/bonus/render/vect_ops_bonus.c
  src/bonus/render/view_transform_bonus.c
Labels: enhancement

#64 Phong refactoring & checker draft
  Makefile
  include/bonus/minirt_bonus.h
  include/bonus/structs_bonus.h
  include/mandatory/minirt.h
  include/mandatory/structs.h
  src/bonus/parse/obj_lst_bonus.c
  src/bonus/render/apply_texture_bonus.c
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/intersect_cy_bonus.c
  src/bonus/render/intersect_cy_circle_bonus.c
  src/bonus/render/intersect_pl_bonus.c
  src/bonus/render/intersect_sph_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/mandatory/render/intersect_cy.c
  src/mandatory/render/intersect_cy_circle.c
  src/mandatory/render/intersect_pl.c
  src/mandatory/render/intersect_sph.c
  src/mandatory/render/phong_light.c
  src/mandatory/render/phong_util.c
Labels: enhancement

#68 🩹 fix phong reflect and cone
  etc/rt/cn_basic.rt
  etc/rt/cn_test.rt
  etc/rt/cy_test.rt
  include/bonus/minirt_bonus.h
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/intersect_pl_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/bonus/render/shadow_bonus.c
  src/bonus/render/view_transform_bonus.c
  src/mandatory/render/phong_light.c
  src/mandatory/render/phong_util.c
Labels: bug, enhancement

#78 b_fix : Problem in reflection light #66
  etc/rt/cn_test.rt
  include/bonus/minirt_bonus.h
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cy_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/ray_tracing_bonus.c
  src/bonus/render/shadow_bonus.c
  src/bonus/render/view_transform_bonus.c
Labels: enhancement

#80 b_fix : 🩹 Fix inequality to signbit or fpclassify #79
  etc/rt/cn_test.rt
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/intersect_cy_bonus.c
  src/bonus/render/intersect_cy_circle_bonus.c
  src/bonus/render/intersect_pl_bonus.c
  src/bonus/render/intersect_sph_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/shadow_bonus.c
  src/bonus/render/vect_ops_bonus.c
  src/bonus/render/view_transform_bonus.c
Labels: enhancement

#83 Fix reflection and double inequality #82 #79
  etc/rt/cn_test.rt
  etc/rt/cy_test.rt
  include/mandatory/minirt.h
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/shadow_bonus.c
  src/mandatory/render/intersect_cy.c
  src/mandatory/render/intersect_cy_circle.c
  src/mandatory/render/intersect_pl.c
  src/mandatory/render/intersect_sph.c
  src/mandatory/render/phong_light.c
  src/mandatory/render/phong_util.c
  src/mandatory/render/vect_ops.c
Labels: enhancement

#90 b_fix : NO_TXT plane disappears when there are TXT applied objs #76
  include/bonus/minirt_bonus.h
  src/bonus/parse/txt_to_objs_bonus.c
  src/bonus/render/apply_texture_bonus.c
  src/bonus/render/obj_texture_bonus.c
  src/bonus/render/ray_tracing_bonus.c
Labels: enhancement

#91 Fix sphere texture rotation #89
  etc/rt/earth.rt
  etc/rt/sadjule.rt
  etc/rt/texture.rt
  include/bonus/minirt_bonus.h
  src/bonus/parse/fill_sph_pl_bonus.c
  src/bonus/render/apply_texture_bonus.c
  src/bonus/render/cam_hook_bonus.c
  src/bonus/render/clone_rt_bonus.c
  src/bonus/render/get_coord_sys_bonus.c
  src/bonus/render/hook_minirt_bonus.c
  src/bonus/render/obj_texture_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/bonus/render/view_transform_bonus.c
Labels: enhancement

#94 etc : sync bonus and mandatory #87
  etc/rt/cn_test.rt
  etc/rt/sph.rt
  etc/rt/test_shadow.rt
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/intersect_cn_circle_bonus.c
  src/bonus/render/intersect_cy_bonus.c
  src/bonus/render/intersect_cy_circle_bonus.c
  src/bonus/render/intersect_sph_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/phong_util_bonus.c
  src/mandatory/render/cam_hook.c
  src/mandatory/render/intersect_cy.c
  src/mandatory/render/intersect_cy_circle.c
  src/mandatory/render/intersect_pl.c
  src/mandatory/render/intersect_sph.c
  src/mandatory/render/phong_light.c
  src/mandatory/render/phong_util.c
Labels: enhancement

#103 🩹 cone in light display part of cone #101
  etc/rt/cn_test.rt
  src/bonus/render/intersect_cn_bonus.c
  src/bonus/render/phong_light_bonus.c
  src/bonus/render/shadow_bonus.c
Labels: help wanted
